### ISSUE TITLE
Can't download egg of certifi in buildout

### ISSUE THREAD

**Issue by yinlinzh** [certifi/certifi.io#11]
Hi,

When I'm using buildout for code build, there is one error:
Can't download https://pypi.python.org/packages/source/c/certifi/certifi-2016.9.26.tar.gz#md5=baa81e951a29958563689d868ef1064d: 404 Not Found

Would you please take a look?

**Comment by Lukasa** [comment]
It looks to me like this is the result of the change in the PyPI URL scheme [here](https://bitbucket.org/pypa/pypi/issues/438/backwards-compatible-un-hashed-package). This seems to be a buildout-specific problem: they haven't updated to the new URI scheme, which would mean requesting files from `https://files.pythonhosted.org/packages/source/c/certifi/certifi-2016.9.26.tar.gz` (identical to the original URL but with the hostname `files.pythonhosted.org` instead of `pypi.python.org`).

As a result, this is not a certifi issue. Please file a bug report with buildout, or update your buildout if they have already fixed this problem.
