### ISSUE TITLE
certifi.io is down

### ISSUE THREAD

**Issue by gdubicki** [certifi/certifi.io#12]
http://downforeveryoneorjustme.com/certifi.io says:

"It's not just you! http://certifi.io looks down from here."

:P

And it has been down for at least a few days.

Is there any way I can help you guys?

**Comment by Lukasa** [comment]
Yeah, certifi.io is down for the moment due to some...uh...disagreements with our hosting provider. Without wanting to get too far into it, while Rackspace has very kindly hosted our site for free, they seem to occasionally bump into trouble with remembering that it's supposed to be free and attempt to bill us. This time we didn't catch it in time, so the server is gone.

At this point we're planning to take Rackspace out of the mix. The site will be back eventually, but in the meantime it's available at https://certifiio.readthedocs.io until such time as we can get that sorted.

**Comment by rud-bookbites** [comment]
Kind suggestion: maybe change the link in the project description here and on the pip index for the package? 

As an aside, I think github pages might be able to serve this static site without any trouble, fwiw.

**Comment by april** [comment]
@Lukasa, do you know how much traffic the cert bundle and documentation was generating?  I can always ask my employer (Mozilla) if they'd be willing to host.

**Comment by Lukasa** [comment]
I don't, but @kennethreitz might.

**Comment by kennethreitz** [comment]
Not enough traffic to host it. It was down for months before anyone noticed.

**Comment by april** [comment]
Ahh, does that mean you're not looking for hosting then?  If that's the case, I believe DNSimple offers redirection such that you could simply redirect certifi.io to readthedocs.  It confused me today when trying to find things, because the GitHub repo linked to certifi.io.  :)

**Comment by kennethreitz** [comment]
fixed!

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by april** [comment]
Awesome, thank you!
